export const countries = [
  { name: "Afghanistan", iso: "AF", dialCode: "+93" },
  { name: "Argentina", iso: "AR", dialCode: "+54" },
  { name: "Australia", iso: "AU", dialCode: "+61" },
  { name: "Austria", iso: "AT", dialCode: "+43" },
  { name: "Bangladesh", iso: "BD", dialCode: "+880" },
  { name: "Belgium", iso: "BE", dialCode: "+32" },
  { name: "Bhutan", iso: "BT", dialCode: "+975" },
  { name: "Brazil", iso: "BR", dialCode: "+55" },
  { name: "Canada", iso: "CA", dialCode: "+1" },
  { name: "China", iso: "CN", dialCode: "+86" },
  { name: "Colombia", iso: "CO", dialCode: "+57" },
  { name: "Denmark", iso: "DK", dialCode: "+45" },
  { name: "Egypt", iso: "EG", dialCode: "+20" },
  { name: "Finland", iso: "FI", dialCode: "+358" },
  { name: "France", iso: "FR", dialCode: "+33" },
  { name: "Germany", iso: "DE", dialCode: "+49" },
  { name: "Ghana", iso: "GH", dialCode: "+233" },
  { name: "Greece", iso: "GR", dialCode: "+30" },
  { name: "Hong Kong", iso: "HK", dialCode: "+852" },
  { name: "India", iso: "IN", dialCode: "+91" },
  { name: "Indonesia", iso: "ID", dialCode: "+62" },
  { name: "Ireland", iso: "IE", dialCode: "+353" },
  { name: "Israel", iso: "IL", dialCode: "+972" },
  { name: "Italy", iso: "IT", dialCode: "+39" },
  { name: "Japan", iso: "JP", dialCode: "+81" },
  { name: "Kenya", iso: "KE", dialCode: "+254" },
  { name: "Malaysia", iso: "MY", dialCode: "+60" },
  { name: "Mexico", iso: "MX", dialCode: "+52" },
  { name: "Nepal", iso: "NP", dialCode: "+977" },
  { name: "Netherlands", iso: "NL", dialCode: "+31" },
  { name: "New Zealand", iso: "NZ", dialCode: "+64" },
  { name: "Nigeria", iso: "NG", dialCode: "+234" },
  { name: "Norway", iso: "NO", dialCode: "+47" },
  { name: "Pakistan", iso: "PK", dialCode: "+92" },
  { name: "Philippines", iso: "PH", dialCode: "+63" },
  { name: "Poland", iso: "PL", dialCode: "+48" },
  { name: "Portugal", iso: "PT", dialCode: "+351" },
  { name: "Qatar", iso: "QA", dialCode: "+974" },
  { name: "Russia", iso: "RU", dialCode: "+7" },
  { name: "Saudi Arabia", iso: "SA", dialCode: "+966" },
  { name: "Singapore", iso: "SG", dialCode: "+65" },
  { name: "South Africa", iso: "ZA", dialCode: "+27" },
  { name: "South Korea", iso: "KR", dialCode: "+82" },
  { name: "Spain", iso: "ES", dialCode: "+34" },
  { name: "Sri Lanka", iso: "LK", dialCode: "+94" },
  { name: "Sweden", iso: "SE", dialCode: "+46" },
  { name: "Switzerland", iso: "CH", dialCode: "+41" },
  { name: "Thailand", iso: "TH", dialCode: "+66" },
  { name: "Turkey", iso: "TR", dialCode: "+90" },
  { name: "Ukraine", iso: "UA", dialCode: "+380" },
  { name: "United Arab Emirates", iso: "AE", dialCode: "+971" },
  { name: "United Kingdom", iso: "GB", dialCode: "+44" },
  { name: "United States", iso: "US", dialCode: "+1" },
  { name: "Vietnam", iso: "VN", dialCode: "+84" },
];